---
# tasks file for ansible-role-awscli

- name: Install python pip
  apt:
    name: python-pip
    state: present
    update_cache: yes

- name: Install awscli
  pip:
    name: awscli
    state: present

- name: Create the aws config directory
  become: yes
  become_user: "{{ item.name }}"
  file:
    path: ~/.aws
    state: directory
    mode: 0755
  with_items: "{{ awscli_users }}"
  when: item.state is not defined or item.state == "present"

- name: Set awscli credentials
  become: yes
  become_user: "{{ item.name }}"
  template:
    src: config.j2
    dest: ~/.aws/config
    mode: 0600
  with_items: "{{ awscli_users }}"
  when: item.state is not defined or item.state == "present"

- name: Set awscli credentials
  become: yes
  become_user: "{{ item.name }}"
  template:
    src: credentials.j2
    dest: ~/.aws/credentials
    mode: 0600
  with_items: "{{ awscli_users }}"
  when: item.state is not defined or item.state == "present"

- name: Remove awscli
  become: yes
  become_user: "{{ item.name }}"
  file:
    path: ~/.aws
    state: absent
  with_items:
    - "{{ awscli_users }}"
  when: item.state is defined and item.state == "absent"
